// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package grpc.greeting;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.greeting.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string secondName = 2;</code>
   */
  String getSecondName();
  /**
   * <code>string secondName = 2;</code>
   */
  com.google.protobuf.ByteString
      getSecondNameBytes();
}
